### ISSUE TITLE
snip and pvt_ip mixed up?

### ISSUE THREAD

**Issue by pieterbuytaert** [citrix/citrix-adc-azure-templates#2]
in the custom_data on the virtual machine deploys I can see that snip_11 and pvt_ip_12 is passed to the virtual machine as cloud init.

isn't it strange that subnet11 is described in variables as client side subnet, but passed to the VM as snip, and that subnet12 is described in variables as server side subnet, but passed as private IP?

I ran into this issue when trying to rework this template to Terraform

**Comment by sumanth-lingappa** [comment]
Thank you for rising this issue @pieterbuytaert .
We will look into this.

To streamline, can you please let us know the template you are trying to deploy?

**Comment by sumanth-lingappa** [comment]
closing the issue. Pease reopen the issue with more details. thank you
