### ISSUE TITLE
Private VIP

### ISSUE THREAD

**Issue by ctahok** [citrix/citrix-adc-azure-templates#9]
It is not possible to deploy the template in an environment where public IPs are not allowed by Azure policies. 
Is it possible to change the template to deploy it with private IP as title suggests?

**Comment by ctahok** [comment]
No one?

**Comment by sumanth-lingappa** [comment]
Hello @ctahok , thank you for your questions.
Apologise for the late reply.

Can you please elaborate?
Which template are you trying to deploy?

**Comment by sumanth-lingappa** [comment]
closing the issue. Please reopen the issue with more details. Thank you
